# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastsql',
                'doc_host': 'https://fastai.github.io',
                'git_url': 'https://github.com/fastai/fastsql',
                'lib_path': 'fastsql'},
  'syms': { 'fastsql.core': { 'fastsql.core.Connection.sql': ('core.html#connection.sql', 'fastsql/core.py'),
                              'fastsql.core.CursorResult.tuples': ('core.html#cursorresult.tuples', 'fastsql/core.py'),
                              'fastsql.core.MetaData.__dir__': ('core.html#metadata.__dir__', 'fastsql/core.py'),
                              'fastsql.core.MetaData.close': ('core.html#metadata.close', 'fastsql/core.py'),
                              'fastsql.core.MetaData.sql': ('core.html#metadata.sql', 'fastsql/core.py'),
                              'fastsql.core.ReadOnlyColumnCollection.__dir__': ( 'core.html#readonlycolumncollection.__dir__',
                                                                                 'fastsql/core.py'),
                              'fastsql.core.Table.get': ('core.html#table.get', 'fastsql/core.py'),
                              'fastsql.core._getattr_': ('core.html#_getattr_', 'fastsql/core.py'),
                              'fastsql.core.conn_db': ('core.html#conn_db', 'fastsql/core.py')}}}
